name: tempBanPlugin
version: '1.0'
main: org.tempBanPlugin.tempBanPlugin.TempBanPlugin
api-version: '1.21'
authors: [ Crasyman2 and vincentjm12 ]
description: This plugin creates a temporary ban for all players who die.

